version: 2

multi-ecosystem-groups:
  plugin-dependencies:
    target-branch: "dev"
    schedule:
      interval: "weekly"

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "plugin-dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "plugin-dependencies"
